In [1]:
import spacy
import pandas as pd
import pandas as pd
df=pd.read_csv("freedom_bank_aktau.csv", encoding="utf-8-sig")
nlp = spacy.load("ru_core_news_sm")  # если отзывы на русском

def extract_persons(text):
    if not isinstance(text, str):
        return []
    
    doc = nlp(text)
    
    return [
        ent.text.strip()
        
        for ent in doc.ents
        if ent.label_ == "PER" or ent.label_ == "PERSON"
    ]


df["люди"] = df["текст"].apply(extract_persons)

In [2]:
df["review_id"] = df.index

In [3]:
import re
import numpy as np

def clean_people(x):
    if not isinstance(x, str):
        return np.nan   # пустое сохраняем как NaN

    x = x.lower().replace('\xa0', ' ')
    x = re.sub(r'[^\w\s]', '', x)

    tokens = x.split()

    # убираем мусорные токены (роли и т.п.)
    bad = {
        "менеджер", "ментор", "преподаватель",
        "саппорт", "академия", "финанс", "брокер",
        'самый',"супервайзер","маман","оте"
    }

    tokens = [t for t in tokens if t not in bad and len(t) > 1]

    if len(tokens) == 0:
        return np.nan

    return " ".join(tokens)

In [4]:
df['people']=df['люди']

In [5]:
df["people"] = df["people"].apply(clean_people)

In [6]:
df

,дата,время,рейтинг,текст,автор,likes_count,official_answer,город,люди,review_id,people
0,2026-04-23,12:19:50,5,Дархан ханымға алғысым шексіз. Өз ісінің маман...,Кашмар,0,{'date_created': '2026-04-23T15:08:05.654567+0...,Актау,[Көп],0,NaN
1,2026-04-22,15:55:16,1,Худший из худших закрыли карту жены и не откры...,Babek Fatullayev,0,{'date_created': '2026-04-23T04:11:24.794783+0...,Актау,[],1,NaN
2,2026-04-22,15:43:46,1,Банк с самым наихудшим сервисом и наглыми прав...,Shinigami kz,1,{'date_created': '2026-04-23T04:10:45.800083+0...,Актау,[],2,NaN
3,2026-04-22,15:26:10,1,"Самый ужасный банк который есть на свете, кото...",Гулбакыт Откилбаева,1,{'date_created': '2026-04-22T19:52:18.529767+0...,Актау,[],3,NaN
4,2026-04-20,14:40:55,1,"Они очень плохо помогают иностранцам, а обменн...",Anel Zhum,1,{'date_created': '2026-04-20T16:54:39.090161+0...,Актау,[],4,NaN
...,...,...,...,...,...,...,...,...,...,...,...
673,2022-11-03,12:43:07,3,Еліміздегі ең керемет банктердің алдыңғы қатар...,Саллахадин Аль-Аюб,1,{'date_created': '2022-11-03T18:21:39.100777+0...,Актау,"[бір бөлек, рәсімдеген болатынбыз, ешқайда шық...",673,NaN
674,2022-11-02,16:47:37,5,Саламатсызба жұмыстарыңыз жақсы жүріп жатр раз...,Куаныш Асанов,1,{'date_created': '2022-11-03T18:17:16.812689+0...,Актау,"[Саламатсызба, алла берекетін, сіздерге осылай]",674,NaN
675,2022-10-20,19:14:23,1,Обратился в банк 7 октября для открытия мульти...,Дмитрий Сумской,0,{'date_created': '2022-10-20T20:45:43.432525+0...,Актау,[],675,NaN
676,2022-10-17,18:34:53,1,"Сервис просто никакой, сотрудники некомпитентн...",Михаил Калашников,0,{'date_created': '2022-10-17T20:40:07.266862+0...,Актау,[],676,NaN
677,2022-10-17,18:21:24,1,Я Думал на сегодня таких банков уже не встрети...,Тахир Ибрагимов,0,{'date_created': '2022-10-17T20:34:37.952377+0...,Актау,"[Думал, Каспий]",677,NaN

In [299]:
df=df.explode('people')

In [300]:
print(df['people'].unique())

[nan 'Перизат' 'Карэн' 'Авиа' 'Тыныбекову Ануару\nЖелаю' 'Шанхай-Алматы'
 'Фридома' 'Фридом' '🤦🏻\u200d♀' 'Александре' 'Айжан' 'багаж'
 'Фридом Тревел' 'Ещё' 'Нуржан' 'Ерканатулы Жанарысу' 'Фридом Тревелу'
 'Тай' 'Фридом Трэвел' 'булар маған' 'ескерту жасамай ушаа алмай калдым'
 'ала алмай' 'Бұл' 'Ура' 'Тимура' 'Фридом Банка' 'возьмите курсы' 'Дарья'
 'Благо' 'Авиаты' 'Жанель' 'новый)Карен' 'Максиму' 'Вами' 'Анель'
 'Светлана' 'Гагарина' 'Колл' 'бірақ соңғы' 'дегенбі басам' 'ван лав'
 'Дана' 'Өте' 'екен' 'Фурманова' 'Марий' 'Эйр Астаны' 'Алматы Астана'
 'Наргиз' 'Алматы Новосибирск' 'Решил' 'да мүмкін' '🤦🏻\u200d♀️'
 'Алматы - Атырау' 'Тобаякова' 'Рустаму' 'Алянур Кургамбекова'
 'Алина Лутфулла-Ходжаева' 'Аюна' 'өткізе алмай' 'Сижу' 'Блин'
 'Алматы Медина' 'Авиата' 'Раз Вы' 'ба Мен' 'откенмин ба' 'Алматы'
 'Авиате' 'Адилет' 'Альбина' 'Билет' 'Уму' 'салеметсиз бе' 'калай канша'
 'алуга болады' 'Атырауга' 'алуга болама' 'Билетімді' 'Брон' 'али акшасын'
 'ала алмай отырмыз,2 айдан' 'Маган' 'өте көп' 'Құзырлы органға' 'Бек'
 'Атырау Актау' 'Ух' 'Бек Эир' 'Авдинова Расула Анварулы' 'Султанов Серик']

In [308]:
import re

phrase_to_remove = {
    'бек эир',
    'ескерту жасамай ушаа алмай калдым',
    'шанхай алматы',
    'ала алмай',
    "булар маған", "билетімді тауып", "возьмите курсы", "дегенбі басам",
    'ван лав','фурманова','эйр астаны','алматы астана','алматы новосибирск',
    'да мүмкін','алматы атырау','бірақ соңғы','өткізе алмай','алматы медина',
    'раз вы','ба мен','откенмин ба','салеметсиз бе',
    'калай канша','алуга болады','алуга болама','али акшасын',
    'отырмыз айдан', 'құзырлы органға', 'атырау актау',

    
}

word_to_remove = {
    'тревел', 'авиата', 'авиаты',
    'атырауга', 'авиа', 'тревелу', 'фридома', "багаж","ещё",
    "трэвел","тай", "банка", "бұл", "ура", 'вами', "благо","екен",
    "решил", "гагарина", 'сижу','блин','алматы','авиате',
    'билет','уму','брон','маган', 'бек', 'ух'
}


import re
import numpy as np

phrase_to_remove = {p.lower() for p in phrase_to_remove}
word_to_remove = {w.lower() for w in word_to_remove}

def clean(name):
    if not isinstance(name, str):
        return np.nan

    name = name.lower()
    name = name.replace('\xa0', ' ')

    # --- 1. фразы (через regex безопаснее, чем replace)
    for ph in phrase_to_remove:
        name = re.sub(r'\b' + re.escape(ph) + r'\b', ' ', name)

    # --- 2. убрать пунктуацию
    name = re.sub(r'[^\w\s]', ' ', name)

    tokens = name.split()

    cleaned = []
    for t in tokens:
        if (
            t in word_to_remove or
            len(t) <= 1 or
            t.isdigit()
        ):
            continue
        cleaned.append(t)

    if len(cleaned) == 0:
        return np.nan


    return " ".join(cleaned)

In [309]:
df['people']=df['people'].apply(clean)

In [311]:
import re

def normalize_token(t):
    t = t.lower().strip()
    t = re.sub(r'[^\w\s]', '', t)

    # лёгкое снятие типичных окончаний (очень важно для RU/KZ данных)
    for suf in ["ом", "ым", "ему", "е", "у", 'ға', 'тың', 'ның']:
        if len(t) > 5 and t.endswith(suf):
            t = t[:-len(suf)]
            break

    return t
def normalize_person(name):
    if not isinstance(name, str):
        return name

    name = name.lower()
    name = name.replace('\xa0', ' ')
    name = re.sub(r'[^\w\s]', '', name)

    tokens = [normalize_token(t) for t in name.split()]
    
    # убираем пустые
    tokens = [t for t in tokens if len(t) > 1]

    if len(tokens) == 0:
        
        return None

    # сортировка убирает проблему "евгений каримов" vs "каримов евгений"
    tokens = sorted(tokens)

    return " ".join(tokens)
df["people_clean"] = df["people"].apply(normalize_person)

In [314]:
df['people_clean'].value_counts()

people_clean
перизат                    4
айжан                      3
карэн                      2
дарья                      2
ануар тыныбеков            1
александр                  1
нуржан                     1
ерканатулы жанарыс         1
тимур                      1
жанель                     1
максим                     1
анель сулейменова          1
светлана                   1
дана                       1
марий                      1
наргиз                     1
тобаякова                  1
рустам                     1
алянур кургамбекова        1
алина лутфулла ходжаева    1
аюна                       1
адилет                     1
альбина                    1
анварулы расул             1
серик султанов             1
Name: count, dtype: int64

In [313]:
def normalize_name(name):
    mapping = {
        'ануар желаю тыныбеков':'ануар тыныбеков',
        'карен новый': 'карэн',
        'тимура':'тимур',
        'авдинова анварулы расула':'анварулы расул',
        'айзер':'айзере',
        'жадыр':'жадыра',
        'айше':'айша',
        'динар':'динара',
        'армана':'арман',
        'сабира':'сабира тынышбай',
        'ажар':'ажар жайлаубай',
        'ажарга':'ажар жайлаубай',
        'анель':'анель сулейменова',
        'анель сулейменовой':'анель сулейменова'
    }
    return mapping.get(name, name)
import numpy as np

def safe_normalize(x):
    if isinstance(x, str):
        return normalize_name(x)

    return np.nan
df["people_clean"] = df["people_clean"].apply(safe_normalize)

In [251]:
df

,дата,время,рейтинг,текст,автор,likes_count,official_answer,отделение,люди,review_id,people,people_clean
0,2026-04-20,19:50:45,1,Специалисты так и не связались 😒,W221 Designo,0,NaN,"Freedom Insurance, Проспект Аль-Фараби",[],0,NaN,NaN
1,2026-04-17,16:12:47,1,Две недели уже тянут придумывают каждый день ч...,Сергей Довбенко,0,NaN,"Freedom Insurance, Проспект Аль-Фараби",[],1,NaN,NaN
2,2026-04-10,19:46:59,5,1 ай бұрын ДТП болған еді сол уақыттан бері ко...,Бекзат Тлеухан,0,{'date_created': '2026-04-18T21:47:54.76936+07...,"Freedom Insurance, Проспект Аль-Фараби",[Уали Қарақат],2,уали қарақат,уали қарақат
3,2026-04-10,15:37:13,1,"Пользоваться Вашими услугами сплошной стресс, ...",Anar Abuova,0,NaN,"Freedom Insurance, Проспект Аль-Фараби",[Вами],3,NaN,NaN
4,2026-04-08,13:37:16,5,Очень благодарен Замире за оказанную ею помощь...,иван сотников,0,{'date_created': '2026-04-18T21:50:59.266234+0...,"Freedom Insurance, Проспект Аль-Фараби",[Замире],4,замире,замир
...,...,...,...,...,...,...,...,...,...,...,...,...
204,2025-03-06,19:24:34,1,Отличное заведение. В 17-15 менеджер уже отпро...,Евгений Пятышев,2,NaN,"Freedom Insurance, ЖК Гагарина",[],204,NaN,NaN
205,2025-02-03,15:27:41,1,Ужасно просто нет слов самая просто ДНО а не к...,Шерхан Ходжахметов,3,NaN,"Freedom Insurance, ЖК Гагарина",[],205,NaN,NaN
206,2024-10-11,09:29:28,1,"Это ужасная компания с которым я работал, то у...",Nick Djum,2,NaN,"Freedom Insurance, ЖК Гагарина",[],206,NaN,NaN
207,2024-08-07,14:46:05,1,"Самая ужасная страховая компания, которую толь...",17 школа У-Ка,7,NaN,"Freedom Insurance, ЖК Гагарина",[],207,NaN,NaN
208,2024-01-26,14:49:45,5,Добро пожаловать!,Назым Ардабаева,1,NaN,"Freedom Insurance, ЖК Гагарина",[],208,NaN,NaN

In [315]:
df.drop(columns=['people', 'люди'], inplace=True)

In [316]:
df_reviews = df.drop_duplicates("review_id")

In [320]:
df_reviews.to_csv('freedom_travel'
'.csv'
                  )

In [317]:
df_reviews.rename(columns={'people_clean': 'люди'}, inplace=True)

C:\Users\Subbota\AppData\Local\Temp\ipykernel_12980\3800704962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reviews.rename(columns={'people_clean': 'люди'}, inplace=True)

In [318]:
df_reviews.drop(columns=['review_id'], inplace=True)

C:\Users\Subbota\AppData\Local\Temp\ipykernel_12980\2352020790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reviews.drop(columns=['review_id'], inplace=True)

In [319]:
df_reviews

,дата,время,рейтинг,текст,автор,likes_count,official_answer,люди
0,2026-04-20,19:28:44,1,Купила билет в пятницу 17/04 в приложении Free...,Nargiz N,0,NaN,NaN
1,2026-04-19,02:04:02,1,Сегодня общалась с оператором Перизат. Полный ...,SJ SJ,0,NaN,перизат
2,2026-04-14,14:16:21,1,Испортили великолепно работающий сервис. Тепер...,Павел П,1,{'date_created': '2026-04-14T18:45:48.531122+0...,NaN
3,2026-04-12,20:42:33,2,Сегодня хотел взять Авиа билет в фридом супер ...,Дархан Дархан,0,{'date_created': '2026-04-14T11:46:35.926325+0...,NaN
4,2026-04-11,21:56:23,5,"Спасибо за оперативное решение вопроса, возник...",Sveta Duanabaeva,0,NaN,ануар тыныбеков
...,...,...,...,...,...,...,...,...
410,2019-05-19,13:39:23,5,Отличный сервис и понятный интерфейс 👍,Местный Житель,0,{'date_created': '2019-05-26T12:18:57.016588+0...,NaN
411,2019-05-18,14:55:03,1,"Я неоднократно звонила, отправила запрос по Wh...",Nagira Kashkenova,0,{'date_created': '2019-05-22T13:33:37.213394+0...,NaN
412,2019-03-19,19:27:58,5,Здесь работают приятные молодые люди😊,Elena Burkovetskaya,0,NaN,NaN
413,2019-03-05,13:47:20,1,"По форс мажорным обстоятельствам, а в частност...",Oxi D,0,{'date_created': '2019-03-05T15:46:40.124959+0...,NaN
414,2018-08-17,01:51:33,4,Здесь всегда билеты дешевле. И вариантов много.,Meruyert Almukhametova,0,NaN,NaN

In [336]:
path='freedom_travel.csv'
df=pd.read_csv(path)

df['отделение']='Freedoom Travel, Проспект Гагарина'
df.drop(columns=['Unnamed: 0'], inplace=True)
df.to_csv(path, index=False)

In [337]:
df.columns

Index(['дата', 'время', 'рейтинг', 'текст', 'автор', 'likes_count',
       'official_answer', 'люди', 'отделение'],
      dtype='object')